USE aaemu_game;
+CREATE TABLE IF NOT EXISTS `telemetry_events` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `occurred_at` DATETIME(6) NOT NULL,
    `received_at` DATETIME(6) NOT NULL,
    `server_name` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `server_build` CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `server_boot_id` BINARY(16) NOT NULL,
    `sequence_no` BIGINT UNSIGNED NOT NULL,
    `event_type` VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `severity` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `account_id` INT UNSIGNED NULL,
    `character_id` INT UNSIGNED NULL,
    `actor_character_id` INT UNSIGNED NULL,
    `target_character_id` INT UNSIGNED NULL,
    `session_id` INT UNSIGNED NULL,
    `correlation_id` BIGINT UNSIGNED NULL,
    `zone_id` INT UNSIGNED NULL,
    `world_id` INT UNSIGNED NULL,
    `skill_id` INT UNSIGNED NULL,
    `quest_id` INT UNSIGNED NULL,
    `quest_act_id` INT UNSIGNED NULL,
    `item_id` INT UNSIGNED NULL,
    `outcome` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
    `value_int` BIGINT NULL,
    `fingerprint` BINARY(32) NULL,
    `payload_json` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_telemetry_source` (`server_boot_id`, `sequence_no`),
    KEY `idx_telemetry_time` (`occurred_at`),
    KEY `idx_telemetry_type_time` (`event_type`, `occurred_at`),
    KEY `idx_telemetry_character_time` (`character_id`, `occurred_at`),
    KEY `idx_telemetry_skill` (`skill_id`, `outcome`, `occurred_at`),
    KEY `idx_telemetry_quest` (`quest_id`, `event_type`, `occurred_at`),
    KEY `idx_telemetry_fingerprint` (`event_type`, `fingerprint`, `occurred_at`),
    CONSTRAINT `chk_telemetry_payload`
        CHECK (`payload_json` IS NULL OR JSON_VALID(`payload_json`))
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
